version: '3'
services:
  ctms-api:
    image: ctms-rest-api # expects the image locally, built using ./build.sh
    depends_on:
      - mongodb
    ports:
      - '8880:80'
    environment:
      - MONGO_HOST=mongodb
  mongodb:
    image: mongo
    command: mongod --noauth
