version: '3'
services:
  ctms-api:
    image: adelaideecoinformatics/ctms-rest-api-docker:latest
    depends_on:
      - mongodb
    ports:
      - '8880:80'
    environment:
      - CRA_MONGO_HOST=mongodb
  mongodb:
    image: mongo
    command: mongod --noauth
