apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ctms-server
spec:
  template:
    metadata:
      labels:
        run: ctms-server
    spec:
      containers:
      - image: adelaideecoinformatics/ctms-rest-api-docker:latest
        name: ctms-pod
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: CRA_MONGO_HOST
          value: ctms-mongo
---
apiVersion: v1
kind: Service
metadata:
  name: ctms-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: ctms-server
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
spec:
  template:
    metadata:
      labels:
        run: ctms-mongodb
    spec:
      containers:
      - image: mongo
        name: mongo-pod
        command:
          - mongod
          - --noauth # FIXME change to using auth
---
apiVersion: v1
kind: Service
metadata:
  name: ctms-mongo
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    run: ctms-mongodb
